FROM test-react-deps

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

WORKDIR /app

COPY .env .
COPY scripts /app/scripts
COPY tests tests
COPY jest-puppeteer.config.js .
COPY tsconfig.json .

USER node

EXPOSE 5175

CMD ["scripts/run-tests.sh"]
