FROM nginx:alpine

RUN rm -f /var/log/nginx/* && mkdir -p /var/log/nginx && chown -R nginx:nginx /var/log/nginx 

COPY nginx.conf /etc/nginx/nginx.conf.template

CMD ["sh", "-c", "envsubst '$API_TARGET' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]